let imagesPathClouds = ['img/cloud1.png', 'img/cloud2.png']
let imagesPathsBg = ['img/bg/0.png', 'img/bg/1.png', 'img/bg/2.png', 'img/bg/3.png', 'img/bg/4.png', 'img/bg/5.png']
let imagePathsWalk = ['img/run/W-21.png', 'img/run/W-22.png', 'img/run/W-23.png', 'img/run/W-24.png', 'img/run/W-25.png', 'img/run/W-26.png'];
let imagePathsIdle = ['img/idle/I-1.png', 'img/idle/I-2.png', 'img/idle/I-3.png', 'img/idle/I-4.png', 'img/idle/I-5.png', 'img/idle/I-6.png', 'img/idle/I-7.png', 'img/idle/I-8.png', 'img/idle/I-9.png'];
let imagePathsJump = ['img/jump/J-31.png', 'img/jump/J-33.png', 'img/jump/J-35.png', 'img/jump/J-39.png'];
let imagesPathHit = ['img/hit/hit1.png', 'img/hit/hit2.png', 'img/hit/hit3.png'];
let imagesBg = [];
let imagesCloud = [];
let imagesJump = [];
let imagesWalk = [];
let imagesIdle = [];
let imagesHit = [];